Algoritmo "antecessor"
// Disciplina   : [Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : algoritmo recebe um número e exibe o antecessor dele
// Autor(a)    : Pedro Henrique
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
n1: real
antecessor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa de exibir o número antecessor")
escreva("Escreva um número")
leia(n1)
antecessor<- n1 - 1
escreva("resultado do programa é:",antecessor)

Fimalgoritmo