Algoritmo "divisao"
// Disciplina   : [Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : Algoritmo recebe dois número, faz a divisão entre eles e exibe
//o resultado
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
n1: real
n2: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa de divisão")
escreval("Escreva um número inteiro para fazer a multplicação")
leia(n1)
escreval("Escreva o segundo número para trazer o resultado")
leia(n2)
resultado<- n1 / n2
escreva("o resultado da divisão é:",resultado)
Fimalgoritmo