Algoritmo "multiplicacao"
// Disciplina   : [Lógica de Programação com visualG]
// Professor   : jailson Santos
// Descrição   : Algoritmo vai receber dois números inteiros, fazer a multiplicação
//entre eles e exibir o resultado
// Autor(a)    : Pedro Henrique
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
n1: inteiro
n2: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa de multiplicação")
escreval("Escreva um número inteiro para fazer a multplicação")
leia(n1)
escreval("Escreva o segundo número para trazer o resultado")
leia(n2)
resultado<- n1 * n2
escreva("o resultado da multiplicação é:",resultado)

Fimalgoritmo