Algoritmo "saldação"
// Disciplina   : [Lógica de Programação com visualG]
// Professor   : jailson Santos
// Descrição   : Algoritmo que recebe o nome do usuario e exibe uma mensgem de
//bom dia
// Autor(a)    : Pedro henrique
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
nome: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite seu nome:")
leia(nome)
escreva("bom dia ",nome)

Fimalgoritmo