Algoritmo "soma"
// Disciplina   : [Lógica de Programação com visualg]
// Professor   : Jailson Santos
// Descrição   : Algoritmo que irá receber 2 numero inteiros, fazer a soma deles
// e exibir o resultado
// Autor(a)    : Pedro Henrique
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
n1: inteiro
n2: inteiro
resultado:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa de soma")
escreval("digite um número inteiro para efetuar a soma")
leia(n1)
escreval("Digite o segundo número inteiro para obter o resultado")
leia(n2)
resultado<- n1 + n2
escreval("o resultado da soma é:",resultado)
Fimalgoritmo