Algoritmo "subtracao"
// Disciplina   : [Lógica de Programação com visualG]
// Professor   : Jailson Santos
// Descrição   : Algoritmo recebe dois numero inteiros, faz a subtração e exibe
// o resultado
// Autor(a)    : Pedro Henrique
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
n1: inteiro
n2: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa de subtração")
escreval("Digite um número inteiro para fazer a subtração")
leia(n1)
escreval("Digite o segundo núemro inteiro para a execução da conta")
leia(n2)
resultado<- n1 - n2
escreval("o resultado da subtração é:",resultado)
Fimalgoritmo