Algoritmo "tomadadedecisaosimples"
// Disciplina   : [ Lógica de Programação com Visualg]
// Professor   : jailson Santos
// Descrição   : Recebe um número e toma um desição simples
// Autor(a)    : Pedro Henrique
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
 numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("programa tomada de desição simples")
 escreval("Digite um valor")
 leia(numero)
 se numero > 10 então
    escreval("número digitado é maior que 10")
 fimse
Fimalgoritmo